# Generated by Django 5.1.6 on 2025-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
