# Generated by Django 5.1.6 on 2025-07-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
